{% set version = "0.3.2" %}

package:
  name: multiurl
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/multiurl/multiurl-{{ version }}.tar.gz
  sha256: 8d412bf8efe823916d289523a0891884dabdac3b30d9304f2f915b0fa94ab4e2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - python-dateutil
    - pytz
    - requests
    - tqdm

test:
  imports:
    - multiurl

about:
  home: https://github.com/ecmwf/multiurl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A package to download several URL as one

extra:
  recipe-maintainers:
    - raybellwaves
