{% set version = "0.3.5" %}

package:
  name: multiurl
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/multiurl/multiurl-{{ version }}.tar.gz
  sha256: c2fb8b85227caa453fa0c9e711c5a83e3fd6d9a30b5010ce8a8a4e872d31211e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - python-dateutil
    - pytz
    - requests
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - multiurl

about:
  home: https://github.com/ecmwf/multiurl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A package to download several URL as one

extra:
  recipe-maintainers:
    - raybellwaves
